import nacl.utils

def generate_random_string(bytes):
	gen_bytes = nacl.utils.random(bytes)
	return ' '.join((f'{n:02x}' for n in gen_bytes))

if __name__ == '__main__':
	x = 64 # Number of bytes to generate
	gen_bytes = nacl.utils.random(x) # Generated bytes
	print(' '.join((f'{n:02x}' for n in gen_bytes)))